import json

def build_resume(profile: dict) -> tuple:
    """
    Build a data analyst resume in markdown and return metadata.
    """
    name = profile.get('name', 'Unknown')
    role = profile.get('role', 'data analyst')
    
    # Data analyst resume always includes SQL, Excel, dashboards, statistics
    skills = ['SQL', 'Excel', 'Dashboards', 'Statistics']
    
    # Do not fabricate employers; use generic placeholders
    experience = [
        {
            'company': 'Company A',
            'role': 'Data Analyst',
            'duration': '2020-2023',
            'description': 'Analyzed data using SQL and Excel, created dashboards, performed statistical analysis.'
        },
        {
            'company': 'Company B',
            'role': 'Junior Data Analyst',
            'duration': '2018-2020',
            'description': 'Assisted with data cleaning, reporting, and dashboard maintenance.'
        }
    ]
    
    # Build markdown
    md = f"# {name}\n\n"
    md += f"**Role:** {role}\n\n"
    md += "## Skills\n\n"
    for skill in skills:
        md += f"- {skill}\n"
    md += "\n## Experience\n\n"
    for exp in experience:
        md += f"### {exp['role']} at {exp['company']}\n"
        md += f"*{exp['duration']}*\n\n"
        md += f"{exp['description']}\n\n"
    md += "\n*This resume was generated by resume_builder. Do not fabricate employers.*\n"
    
    # Metadata with ATS score (simple heuristic based on keyword presence)
    ats_score = 0
    keywords = ['SQL', 'Excel', 'dashboard', 'statistics', 'data', 'analysis']
    for kw in keywords:
        if kw.lower() in md.lower():
            ats_score += 20
    ats_score = min(ats_score, 100)
    
    meta = {
        'ats_score': ats_score,
        'skills': skills,
        'experience_count': len(experience)
    }
    
    return md, meta
